### ISSUE TITLE
Create Model in Mongoose for estimates

### ISSUE THREAD

**Issue by vijaythecoder** [vijaythecoder/c-g-coatings-estimator-api#3]
As an administrator, when creating a new estimate, I want to enter:
- unique job name string
- location string
- int number of square feet (default = , min = 0, mas = )
- list of materials (product string, int unit cost, int coverage per sq ft)
- int number of days (default = )
- int hours worked per day (per worker)
- int labor dollars per hour
- int number of hotel rooms
- int number of hotel nights
- int hotel dollars per night
- int food dollars per day (per worker)
- int number of vehicles 
- int number of miles per vehicle
- float dollars per mile
- list of miscellaneous costs (string desc, int dollars)
- float multiplier

**Comment by DevineniSirisha** [comment]
How do I create a column for the misc costs and list of materials??
